name: CI

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  main:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    container: ghcr.io/mopidy/ci:latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.13", "3.14"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true
      - run: pip install coverage tox
      - run: tox
      - uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          name: ${{ matrix.python }}
          token: ${{ secrets.CODECOV_TOKEN }}
